#!/usr/bin/env bash
#SBATCH -A NAISS2023-22-542 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1 # We're launching 2 nodes with 4 Nvidia T4 GPUs each
#SBATCH -t 0-20:00:00 # wall-time; job killed after that

module load Python/3.10.4-GCCcore-11.3.0
module load TensorFlow/2.11.0-foss-2022a-CUDA-11.7.0
module load matplotlib/3.5.2-foss-2022a
module load scikit-learn/1.1.2-foss-2022a
source /cephyr/users/franktho/Alvis/my_python_v1.0/bin/activate

cd /cephyr/users/franktho/Alvis/regional_inversion/src

python igm_inversion_Sweden_Norway.py
